version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_new
    environment:
      MYSQL_ROOT_PASSWORD: Pratyush@6271
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql